#!/usr/bin/env bash

pacman -S --noconfirm unzip wget 
wget https://dl.nssurge.com/snell/snell-server-v4.0.1-linux-amd64.zip
mkdir /snell
unzip snell-server-v4.0.1-linux-amd64.zip
mv snell-server /snell
chmod +x /snell/snell-server

cat << EOF >/snell/snell-server.conf
[snell-server]
listen = 0.0.0.0:57899
psk = cheatgfw233
ipv6 = false
EOF

cat << EOF > /etc/systemd/system/snell.service
[Unit]
Description=Snell Proxy Service
After=network.target

[Service]
#User=sitao
ExecStart=/snell/snell-server -c /snell/snell-server.conf

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable snell
systemctl start snell
systemctl status snell


