#!/bin/bash

clear
gost_path="/gost/gost"

if [ -f "$gost_path" ]; then
  echo "gost 已存在，无需安装。"
  cd /gost
else
echo "开始安装gost和获取tls证书"
mkdir /gost && cd /gost
wget http://dl.sitao.org/project/gost-linux-amd64-2.11.5.gz
gzip -d gost-linux-amd64-2.11.5.gz
mv gost-linux-amd64-2.11.5 gost
cp gost /usr/bin/gost
chmod +x /usr/bin/gost
cat << EOF > /etc/systemd/system/gost.service
[Unit]
Description=Gost Service
After=network.target nss-lookup.target

[Service]
User=root
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=gost -C /gost/gost.server
Restart=on-failure
RestartPreventExitStatus=23
LimitNPROC=10000
LimitNOFILE=1000000

[Install]
WantedBy=multi-user.target
EOF
systemctl enable gost
mkdir tls/
wget http://dl.sitao.org/project/tls/cert.pem
wget http://dl.sitao.org/project/tls/certkey.pem
cd ..

echo "gost安装成功"
fi



read -p "转发数量： " number
if ! [[ $number =~ ^[0-9]+$ ]]; then
  echo "请输入有效的数字。"
  exit 1
fi

read -p "落地ip:" ip
read -p "中转节点的起始端口:" base_port

config_file="gost.server"

# 清空配置文件
echo -n "" > "$config_file"

# 循环生成节点配置
for ((i = 0; i < number; i++)); do
  serve_port=$((base_port + i))
  chain_port=$((9000 + i))
  config=$(cat <<-END
    {
        "Retries": 3,
        "ServeNodes": [
            "tcp://0.0.0.0:$serve_port"
        ],
        "ChainNodes": [
            "relay+tls://$ip:$chain_port?cert=/gost/tls/cert.pem&key=/gost/tls/certkey.pem"
        ]
    },
END
)
  echo "$config" >>"$config_file"
done

# 添加完整配置格式
sed -i '$ s/,$//' "$config_file"
sed -i '1i {\
"Debug": true,\
"Retries": 3,\
"Routes": [' "$config_file"
echo '    ]' >>"$config_file"
echo '}' >>"$config_file"

echo "已生成配置文件 $config_file。"
echo $config_file 
systemctl start gost
systemctl status gost

